palindromestr.py
value of my_str can be changed to test.
=> Program to check if a string is palindrome or not

dectobin.py
=> Function to print binary number using recursion

lcm2no.py
To test change value of num1 and num2.
=> LCM of 2 no.

charascii.py
=> Program to find the ASCII value of the given character

fibonaciseq.py
To test, change value of nterms.
=> Python program to display the Fibonacci sequence

ctof.py
To test, change value of celsius.
=> Convert Celsius To Fahrenheit.

randnum.py
Genetrates random number between 0-9
=> Program to Generate a Random Number

sum2num.py
=> Add two no.

game.py
this may help you to increase your repository with good codes
=> try to create small game

findhashno.py
To test,  change the hash_file.
=> Program to Find Hash of File

countvowels.py
=> Count vowels in a sentence.

factors.py
=> Program to find the factors of a number

swapvar.py
=> Program to swap two variables.

quadraticeq.py
To test, change the value of a, b and c.
=> Program to Solve Quadratic Equation

productuniqueprime.py
To est, change the value of n.
=> Product of unique prime factors of a number

gpattern.py
To change number of lines, change value of line.
=> Creates pattern 'G'

sumarray.py
=> Sum of an array.

mergesort.py
Merges two subarrays of arr[].
=>  Implementation of MergeSort

times-tables.py
Added A Simple Program to Ask People Their Times Tables
=> Added Times Tables

Genetic Algorithm/Example.py, Genetic Algorithm/Individual.py, Genetic Algorithm/Population.py, Genetic Algorithm/README.md
It's my DIY genetic algorithms to solve finding maximum, minimum points problem.
I also include README.md file to show how this works and how to use it.
=> Add my Genetic Algorithms folder

sumalldict.py
=> Program to find the sum of all items in a dictionary

evennolist.py
=> Program to print even numbers in a list

oddnolist.py
=> Program to print odd numbers in a List

evennorange.py
=> Program to print all odd numbers in a range

.idea/codeStyles/codeStyleConfig.xml, .idea/modules.xml, .idea/pythoncharmers.iml, .idea/vcs.xml, .idea/workspace.xml, linearsearch.py
I added a linear search algorithm to the main list of files.
I hope you like it :)
=> Added a basic linear search algorithm

inverse_matrix.py, linear_equation.py, math_matrix.py, plot_2dmatrix.py, plot_matrix.py
Basic Data Visualisation and Matrix based Programs 
Install numpy and matplotlib to run these:
inverse_matrix.py :
program to find the inverse of a matrix
linear_equation.py :
Program to find solutions to linear equations
math_matrix.py:
Program to plot 1D matrix
plot_2dmatrix.py:
Program to plot 12D matrices
plot_matrix.py:
Program to Plot matrix
Install required libraries using these commands:
pip install numpy
pip install matplotlib
https://github.com/mahadevananair1 :)
=> ADDED: Basic Data Visualisation and Matrix based Programs 

OOPExample2.py
I added another example that uses classes
=> Added another OOP example

simplecardchecker.py
All American Express numbers start with 34 or 37;
most MasterCard numbers start with 51, 52, 53, 54, or 55
(they also have some other potential starting numbers whi
we won’t concern ourselves with for this problem);
and all Visa numbers start with 4.
But credit card numbers also have a
“checksum” built into them,
this is based on Luhn’s Algorithm
THIS can detect card numbers as true or false only
also its one of the beginner Projects submitted for Harvard CS50
course. Feel free to look through it :)
how it works explained HERE:
https://cs50.harvard.edu/x/2020/psets/1/credit/#:~:text=Luhn%E2%80%99s%20Algorithm
https://github.com/mahadevananair1
=> Added: Simple credit card number check

rpsgame.py
It is a simple Rock paper scissors game made using conditional statements and infinite loop so that user can stop the code whenever he wants to.
=> Rock paper scissors game

Rock-Paper-Scissors.py
this is my contribution in hacktoberfest 2020. I just added Rock Paper Scissors  (RPS) game using python with library random. if you like it please label my PR with hacktoberfest accepted, its very helpful for me.
=> Added RPS Game

doublesidestair.py
This code only works for even values of n.
=>  Program to print double sided stair-case pattern

difference(max-min).py, validsubstring.py
Given an array A of integers and an integer K, add any K elements of A to form the maximum(max) sum and the minimum(min) sum and Find D(max-min).
=> Find difference between max sum and min sum.

complexconversion.py, gravity.py
Converts between the 3 forms of complex number representation, algebraic form, polar form, and euler form
=> Converts between the 3 forms of complex number representation

neural-net-from-scratch.py
This PR implements a simple neural network with the following features:
* Trains for learning the XOR function
* has a 2-input, 2-hidden and 1-output node architecture
* uses backpropagation algorithm using momentum-based gradient descent
* own matrix implementation from scratch (no numpy!)
* 100 epochs
=> Simple 2-layer neural network from scratch

quantum-random-number-generator.py
* This PR generates random numbers using Hadamard quantum gates (more [info here](https://en.wikipedia.org/wiki/Quantum_logic_gate)) . 
* This is emulated in python using the package `projectq` (just `pip install projectq` !).
* More info on context, tutorial and other cool stuff [here](https://dataespresso.com/en/2018/07/22/Tutorial-Generating-random-numbers-with-a-quantum-computer-Python/)!
=> Quantum random number generator using projectq library

floyd-warshall.py
The Floyd Warshall Algorithm is for solving the All Pairs Shortest Path problem. The problem is to find shortest distances between every pair of vertices in a given edge weighted directed Graph.
=> Floyd-Warshall Graph Algorithm

odd-even-subarray.py
You are given an array A of N positive integer values. A subarray of this array is called Odd-Even subarray if the number of odd integers in this subarray is equal to the number  of even integers in this subarray.
Find the number of Odd-Even subarrays for the given array.
=> Added Odd even subarray question

dfs.py
Hi, I have included concept of Depth First Search using Python.
@Graey please review and merge if helpful.
=> Depth first search using Python

random_story.py
It generates a random one line story and was made using python
=> random_story_generator.py

JumpingNumber.py
I have included a jumping number program which checks whether the user input given is jumping number or not.
=> Added jumping number program

valid_palindrome.py
#Hacktoberfest2021
added a python code for valid palindrome
@venkywonka @Graey pls check
=> added valid_palindrome code

pattern.py
please add this pr for hacktoberfest2021
=> python unique pattern
